#! /bin/sh

sxhkd &

bspc config merge_overlapping_monitors true
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2	state=floating
bspc rule -a Kupfer.py	focus=on
bspc rule -a Screenkey	manage=off
bspc rule -a Peek	state=floating
bspc rule -a QjackCtl	desktop='^10'	state=floating

# Polybar
polybar clarkbar -r &
